VARIANT = 2
YEAR_OF_BIRTH = 2004
MONTH_OF_BIRTH = 1
DAY_OF_BIRTH = 14
RULE_VALUE = VARIANT * 11 * YEAR_OF_BIRTH * MONTH_OF_BIRTH * DAY_OF_BIRTH
NUM_OF_VARIABLES = 5
NUM_OF_DIGITS = 2 ** NUM_OF_VARIABLES
ALL_RULES = 2 ** NUM_OF_DIGITS
